language: generic 
sudo: required

services:
    - docker
before_install:
    - docker build -t pinkukumar/docker-react -f Dockerfile.dev .
script:
    docker run -e CI=true pinkukumar/docker-react npm run test -- --coverage