# Add base image

FROM node:alpine

# define work directory

WORKDIR /app

#COPYING package json file

COPY ./package.json ./

# install dependcies

RUN npm install

# Copy all files

COPY ./ ./


# Run Command

CMD ["npm","start"]